#cloud-config

# This is a reusable template for NGINX reverse proxy VM provisioning.
# The string '10.0.1.4' will be replaced dynamically at runtime
# using a Bash script before passing to Azure VM deployment.

package_update: true
package_upgrade: true

packages:
  - nginx

write_files:
  - path: /etc/nginx/sites-available/default
    content: |
      server {
          listen 80;
          location / {
              proxy_pass http://10.0.1.4:5000/;
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection keep-alive;
              proxy_set_header Host $host;
              proxy_cache_bypass $http_upgrade;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }
      }
    owner: root:root
    permissions: '0644'

runcmd:
  - systemctl enable nginx
  - systemctl restart nginx
  - echo "Nginx configured as reverse proxy at $(date)" >> /var/log/cloud-init-success.log
