#cloud-config

# For CICD we have REMOVED: systemctl start BasicMVC.service - Don't start the service as CI/CD will copy the app and start it

# ============================================
# runcmd: Executes shell commands at first boot
# ============================================

runcmd:
  - wget -q https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
  - dpkg -i packages-microsoft-prod.deb
  - apt-get update
  - apt-get install -y dotnet-sdk-9.0 aspnetcore-runtime-9.0
  - mkdir -p /opt/BasicMVC
  - chown -R www-data:www-data /opt/BasicMVC
  - sleep 5
  - systemctl daemon-reload
  - systemctl enable basicMVC.service
  - echo "Cloud-init setup complete" >> /var/log/cloud-init-success.log

write_files:
  - path: /etc/systemd/system/BasicMVC.service
    permissions: '0644'
    owner: root:root
    content: |
      [Unit]
      Description=ASP.NET Core Web Application Service

      [Service]
      WorkingDirectory=/opt/BasicMVC
      Environment=DOTNET_CLI_HOME=/tmp
      ExecStart=/usr/bin/dotnet /opt/BasicMVC/basicMVC.dll
      Restart=always
      RestartSec=10
      KillSignal=SIGINT
      SyslogIdentifier=BasicMVC
      User=www-data
      EnvironmentFile=/etc/BasicMVC.env

      [Install]
      WantedBy=multi-user.target

  - path: /etc/BasicMVC.env
    permissions: '0644'
    owner: root:root
    content: |
      ASPNETCORE_ENVIRONMENT=Production
      DOTNET_PRINT_TELEMETRY_MESSAGE=false
      ASPNETCORE_URLS=http://+:5000

systemd:
  units:
    - name: basicMVC.service
      enabled: true
