#cloud-config

# This cloud-init config provisions a reverse proxy VM running NGINX
# It proxies traffic from the public Internet (port 80) to the internal ASP.NET app

# The string '10.0.1.4' will be replaced dynamically
# by your script to point to the internal private IP of the app VM

package_update: true
package_upgrade: true

packages:
  - nginx  # Installs the NGINX web server

write_files:
  - path: /etc/nginx/sites-available/default
    content: |
      server {
          listen 80;

          # Optional: Hide NGINX version to improve security
          server_tokens off;

          location / {
              proxy_pass http://10.0.1.4:5000/;  #  Will be replaced with app VMs private IP
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection keep-alive;
              proxy_set_header Host $host;
              proxy_cache_bypass $http_upgrade;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }
      }
    owner: root:root
    permissions: '0644'

runcmd:
  - systemctl enable nginx          # Auto-start on reboot
  - systemctl restart nginx         # Start now
  - echo "Nginx configured as reverse proxy at $(date)" >> /var/log/cloud-init-success.log
