#cloud-config

# For CICD we have REMOVED:systemctl start BasicMVC.service - Don't start the service  — CI/CD will copy the app and start it
  # - systemctl start BasicMVC.service

# ============================================
# runcmd: Executes shell commands at first boot
# ============================================

runcmd:
  # Register Microsoft package repository for .NET
  - wget -q https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
  - dpkg -i packages-microsoft-prod.deb
  - apt-get update

  # Install .NET 9 SDK and ASP.NET Core Runtime
  - apt-get install -y dotnet-sdk-9.0 aspnetcore-runtime-9.0

  # Create deployment directory (CI/CD will copy app files later)
  - mkdir -p /opt/BasicMVC
  - chown -R www-data:www-data /opt/BasicMVC

  # Wait briefly to ensure write_files has completed
  - sleep 10

  # Reload systemd to register the service file defined below
  - systemctl daemon-reload

  #  KEEP: Enable the service so it starts on reboot
  - systemctl enable BasicMVC.service
  # - systemctl start BasicMVC.service

  # ==========================
  # Logging and Verification
  # ==========================

  - echo "--- .NET SDKs Installed ---" >> /var/log/cloud-init-success.log
  - dotnet --list-sdks >> /var/log/cloud-init-success.log 2>&1

  - echo "--- .NET Runtimes Installed ---" >> /var/log/cloud-init-success.log
  - dotnet --list-runtimes >> /var/log/cloud-init-success.log 2>&1

  - echo "--- BasicMVC.service Status ---" >> /var/log/cloud-init-success.log
  - systemctl is-enabled BasicMVC.service >> /var/log/cloud-init-success.log 2>&1

  #  Final status message for confirmation
  - echo "Cloud-init completed successfully at $(date)" >> /var/log/cloud-init-success.log

# ============================================
# write_files: Define custom files to be written
# ============================================

write_files:
  #  Systemd service file to control ASP.NET Core app
  - path: /etc/systemd/system/BasicMVC.service
    content: |
      [Unit]
      Description=ASP.NET Core Web Application Service

      [Service]
      WorkingDirectory=/opt/BasicMVC
      Environment=DOTNET_CLI_HOME=/tmp
      ExecStart=/usr/bin/dotnet /opt/BasicMVC/basicmvc.dll
      Restart=always
      RestartSec=10
      KillSignal=SIGINT
      SyslogIdentifier=BasicMVC
      User=www-data
      EnvironmentFile=/etc/BasicMVC.env

      [Install]
      WantedBy=multi-user.target
    owner: root:root
    permissions: '0644'

  # ✅ Environment variables required by the app
  - path: /etc/BasicMVC.env
    content: |
      ASPNETCORE_ENVIRONMENT=Production
      DOTNET_PRINT_TELEMETRY_MESSAGE=false
      ASPNETCORE_URLS=http://+:5000
    owner: root:root
    permissions: '0644'

# ============================================
# systemd: Enables the service on boot
# ============================================

systemd:
  units:
    - name: BasicMVC.service
      enabled: true
