# ASP.NET CI/CD Pipeline for basicMVC App

name: CICD

on:
  push:
    branches:
      - "cicd"  # Triggers the workflow when pushing to this branch
  workflow_dispatch:  # Allows manual execution from GitHub

env:
  APP_NAME: BasicMVC         # Used for service and folder names
  PUBLISH_DIR: /tmp/basicmvc_publish      # Output folder for published app

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build and Publish
        run: |
          dotnet build --no-restore
          dotnet publish -c Release -o ${{ env.PUBLISH_DIR }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-artifacts
          path: ${{ env.PUBLISH_DIR }}

  deploy:
    name: Deploy to Azure VM
    runs-on: self-hosted
    needs: build

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: app-artifacts

      - name: Stop App Service
        run: |
          sudo systemctl stop ${{ env.APP_NAME }}.service

      - name: Replace Existing Deployment
        run: |
          sudo systemctl stop ${{ env.APP_NAME }}.service || true
          sudo rm -rf /opt/${{ env.APP_NAME }} || true
          sudo mkdir -p /opt/${{ env.APP_NAME }}
          sudo cp -r . /opt/${{ env.APP_NAME }}
          sudo chown -R www-data:www-data /opt/${{ env.APP_NAME }}

      - name: Restart App Service
        run: |
          sudo systemctl daemon-reexec
          sudo systemctl start ${{ env.APP_NAME }}.service
          sudo systemctl status ${{ env.APP_NAME }}.service --no-pager
